### ISSUE TITLE
Prismatic Library 3.0.0 is Causing Leather Armor to Appear Gray

### ISSUE THREAD

**Issue by Hacerio** [UselessSolutions/BTA_Babric_PrismaticLibe#3]
![issue](https://github.com/UselessBullets/BTA_Babric_PrismaticLibe/assets/49822188/349518a7-9ca4-4ad2-bc71-27729db739b7)

I have no other mods or texture packs installed in the example image.

I don't understand why  this  might happen, but I have confirmed that this is what's causing it.

Currently, the only reason I want to have Prismatic Library installed is to use "Better than Legacy!"

**Comment by UselessBullets** [comment]
oh whoops, accidentally keep some debug assets in.
Fixed in 3.0.1

**Comment by Hacerio** [comment]
> oh whoops, accidentally keep some debug assets in. Fixed in 3.0.1

Confirmed to be fixed, no more gray leather - thank you!
